name: Commit Diario

on:
  schedule:
    - cron: '0 0 * * *'   # 00:00 UTC (7:00 PM 
    - cron: '0 4 * * *'   # 04:00 UTC (11:00 PM COL)
    - cron: '0 8 * * *'   # 08:00 UTC (3:00 AM COL)
    - cron: '0 12 * * *'  # 12:00 UTC (7:00 AM COL)
    - cron: '0 16 * * *'  # 16:00 UTC (11:00 AM COL)
    - cron: '0 20 * * *'  # 20:00 UTC (3:00 PM COL)
  workflow_dispatch:

jobs:
  commit-diario:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PIT }}

      - name: Configurar nombre y correo del autor del commit
        run: |
          git config user.name "AndresContreras1034"
          git config user.email "contrerandres001@gmail.com"

      - name: Actualizar archivo de última actualización
        run: |
          echo "Última actualización: $(date -u)" > ultima_actualizacion.txt

      - name: Confirmar y hacer commit
        run: |
          git add ultima_actualizacion.txt
          git commit -m "⏰ Commit automático - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push
