name: Commit Diario

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  commit-diario:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PIT }}

      - name: Configurar nombre y correo del autor del commit
        run: |
          git config user.name "AndresContreras1034"
          git config user.email "contrerandres001@gmail.com"

      - name: Actualizar archivo de última actualización
        run: |
          echo "Última actualización: $(date -u)" > ultima_actualizacion.txt

      - name: Confirmar y hacer commit
        run: |
          git add ultima_actualizacion.txt
          git commit -m "⏰ Commit automático - $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No hay cambios para commitear"
          git push https://x-access-token:${{ secrets.PIT }}@github.com/AndresContreras1034/TU_REPO.git
