name: Commit Diario

on:
  schedule:
    - cron: '0 13 * * *'  # Se ejecuta todos los días a las 8:00 AM Colombia (13 UTC)
  workflow_dispatch:

jobs:
  commit-diario:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PIT }}

      - name: Configurar nombre y correo del autor del commit
        run: |
          git config user.name "AndresContreras1034"
          git config user.email "contrerandres001@gmail.com"

      - name: Actualizar archivo de última actualización
        run: |
          echo "Última actualización: $(date)" > ultima_actualizacion.txt

      - name: Confirmar y hacer commit
        run: |
          git add ultima_actualizacion.txt
          git commit -m "🌞 Commit diario automático - $(date +'%Y-%m-%d')"
          git push
